name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: install packages
      run: |
        sudo apt update -qq
	sudo apt install -y gcc-10 make
	
    - name: build application
      run: make -k